ATG Report On Digital Test Section sy:\0653D_mezzanine.dtp 22-APR-09 15:52:37 
(Task: dtg.exe version 494 Fri Jan 16 22:18:21 Eastern Daylight Time 2009)
User Library: c:\tellabs\tellabslib.dtl
Creation Date: 20-APR-09 18:53:36
Revision Date: 22-APR-09 15:43:32

System Library: 228lib:diglib8x.dtl
Creation Date: 25-MAR-08 13:37:56
Revision Date: 25-MAR-08 15:50:03
------------------------------------------------------------------------------
BOARD STATISTICS SUMMARY

	Device count		1761
	Digital IC count	   6
Target tester: 2287		Adaptor specified for: 2287
Isolation level:           1
Bustest isolation level:   1
SPF isolation:             NONE
Floating DUT inputs:       ID
Isolation selection order: AUTO
Lowest nail used     1
Highest nail used 1729


Logic Level Assignments for Nails
	 LVLA(1-1729)

Results for Non-bussed ICs
--------------------------
** WARNING: Did not find any valid output statement (OS) for U2.
At least one valid output statement(OS) is required for a test to be generated



-------------------------------------------
PIN RESULTS FOR U2 (VSC9186)
	 Pin  Type   Nail  Tested?  Comments
	 A4   IN      804    NO 
	 A5   IN      804    NO 
	 A6   IN      779    NO 
	 A7   IN   
	 A8   IN      779    NO 
	 A9   IN      602    NO 
	 A10  IN     1604    NO 
	 A11  IN     1588    NO 
	 A12  IN      684    NO 
	 A13  IN      739    NO 
	 A14  IN      723    NO 
	 A15  IN       41    NO 
	 A16  IN     1548    NO 
	 A17  IN      732    NO 
	 A18  IN       10    NO 
	 A19  IN      747    NO 
	 A20  IN       18    NO 
	 A21  IN      755    NO 
	 AA1  IN     1284    NO 
	 AA2  IN   
	 AA3  IN     1652    NO 
	 AA4  IN     1332    NO 
	 AA5  IN     1403    NO 
	 AA6  IN     1396    NO 
	 AA7  IN     1620    NO 
	 AA8  IN       11    NO      FORCED HI
	 AA9  IN   
	 AA10  IN      537    NO 
	 AA11  IN      385    NO 
	 AA12  IN      529    NO 
	 AA13  IN      449    NO 
	 AA14  IN      138    NO 
	 AA15  IN      402    NO 
	 AA16  IN       11    NO      FORCED HI
	 AA17  IN       11    NO      FORCED HI
	 AA18  IN      122    NO 
	 AA19  IN      305    NO 
	 AA20  IN      137    NO 
	 AA21  IN      274    NO 
	 AA22  IN   
	 AA23  IN      225    NO 
	 AA24  IN      185    NO 
	 AB1  IN     1355    NO 
	 AB2  IN       11    NO      FORCED HI
	 AB3  IN     1348    NO 
	 AB4  IN        3    NO      FORCED LOW
	 AB5  IN       11    NO      FORCED HI
	 AB6  IN       83    NO      FORCED HI
	 AB7  IN     1419    NO 
	 AB8  IN        3    NO      FORCED LOW
	 AB9  IN      513    NO 
	 AB10  IN       11    NO      FORCED HI
	 AB11  IN      369    NO 
	 AB12  IN        3    NO      FORCED LOW
	 AB13  IN       83    NO      FORCED HI
	 AB14  IN      554    NO 
	 AB15  IN        3    NO      FORCED LOW
	 AB16  IN      466    NO 
	 AB17  IN       11    NO      FORCED HI
	 AB18  IN      177    NO 
	 AB19  IN        3    NO      FORCED LOW
	 AB20  IN       11    NO      FORCED HI
	 AB21  IN       83    NO      FORCED HI
	 AB22  IN      242    NO 
	 AB23  IN        3    NO      FORCED LOW
	 AB24  IN      194    NO 
	 AC1  IN       11    NO      FORCED HI
	 AC2  IN     1131    NO 
	 AC3  IN       11    NO      FORCED HI
	 AC4  IN     1339    NO 
	 AC5  IN       11    NO      FORCED HI
	 AC6  IN     1643    NO 
	 AC7  IN       11    NO      FORCED HI
	 AC8  IN     1427    NO 
	 AC9  IN      545    NO 
	 AC10  IN      497    NO 
	 AC11  IN      361    NO 
	 AC12  IN      474    NO 
	 AC13  IN      306    NO 
	 AC14  IN      522    NO 
	 AC15  IN   
	 AC16  IN      433    NO 
	 AC17  IN      129    NO 
	 AC18  IN       11    NO      FORCED HI
	 AC19  IN      353    NO 
	 AC20  IN       11    NO      FORCED HI
	 AC21  IN      169    NO 
	 AC22  IN     1716    NO 
	 AC23  IN     1244    NO 
	 AC24  IN        3    NO      FORCED LOW
	 AD1  IN     1100    NO 
	 AD2  IN        3    NO      FORCED LOW
	 AD3  IN     1684    NO 
	 AD4  IN       11    NO      FORCED HI
	 AD5  IN     1404    NO 
	 AD6  IN        3    NO      FORCED LOW
	 AD7  IN       11    NO      FORCED HI
	 AD8  IN       83    NO      FORCED HI
	 AD9  IN      538    NO 
	 AD10  IN        3    NO      FORCED LOW
	 AD11  IN      217    NO 
	 AD12  IN       11    NO      FORCED HI
	 AD13  IN        3    NO      FORCED LOW
	 AD14  IN   
	 AD15  IN       83    NO      FORCED HI
	 AD16  IN      257    NO 
	 AD17  IN        3    NO      FORCED LOW
	 AD18  IN       11    NO      FORCED HI
	 AD19  IN       83    NO      FORCED HI
	 AD20  IN      298    NO 
	 AD21  IN        3    NO      FORCED LOW
	 AD22  IN     1236    NO 
	 AD23  IN       83    NO      FORCED HI
	 AD24  IN     1307    NO 
	 AE1  IN      852    NO 
	 AE2  IN     1124    NO 
	 AE3  IN      667    NO 
	 AE4  IN     1347    NO 
	 AE5  IN     1292    NO 
	 AE6  IN     1356    NO 
	 AE7  IN      570    NO 
	 AE8  IN     1420    NO 
	 AE9  IN      313    NO 
	 AE10  IN      521    NO 
	 AE11  IN       11    NO      FORCED HI
	 AE12  IN      201    NO 
	 AE13  IN      457    NO 
	 AE14  IN     1572    NO 
	 AE15  IN      401    NO 
	 AE16  IN      409    NO 
	 AE17  IN      345    NO 
	 AE18  IN      209    NO 
	 AE19  IN   
	 AE20  IN      170    NO 
	 AE21  IN      234    NO 
	 AE22  IN     1460    NO 
	 AE23  IN     1251    NO 
	 AE24  IN       60    NO      FORCED HI
	 AF1  IN     1107    NO 
	 AF2  IN       83    NO      FORCED HI
	 AF3  IN     1675    NO 
	 AF4  IN        3    NO      FORCED LOW
	 AF5  IN      577    NO 
	 AF6  IN       83    NO      FORCED HI
	 AF7  IN      281    NO 
	 AF8  IN        3    NO      FORCED LOW
	 AF9  IN   
	 AF10  IN       11    NO      FORCED HI
	 AF11  IN      282    NO 
	 AF12  IN        3    NO      FORCED LOW
	 AF13  IN       83    NO      FORCED HI
	 AF14  IN      250    NO 
	 AF15  IN        3    NO      FORCED LOW
	 AF16  IN      377    NO 
	 AF17  IN       11    NO      FORCED HI
	 AF18  IN      146    NO 
	 AF19  IN        3    NO      FORCED LOW
	 AF20  IN      266    NO 
	 AF21  IN       11    NO      FORCED HI
	 AF22  IN     1243    NO 
	 AF23  IN        3    NO      FORCED LOW
	 AF24  IN     1300    NO 
	 AG1  IN      851    NO 
	 AG2  IN     1411    NO 
	 AG3  IN      836    NO 
	 AG4  IN     1219    NO 
	 AG5  IN      820    NO 
	 AG6  IN      562    NO 
	 AG7  IN      314    NO 
	 AG8  IN      329    NO 
	 AG9  IN       11    NO      FORCED HI
	 AG10  IN      441    NO 
	 AG11  IN      780    NO 
	 AG12  IN   
	 AG13  IN      289    NO 
	 AG14  IN      772    NO 
	 AG15  IN      226    NO 
	 AG16  IN      321    NO 
	 AG17  IN   
	 AG18  IN      354    NO 
	 AG19  IN      153    NO 
	 AG20  IN     1492    NO 
	 AG21  IN     1156    NO 
	 AG22  IN     1444    NO 
	 AG23  IN      130    NO 
	 AG24  IN     1428    NO 
	 AH1  IN       11    NO      FORCED HI
	 AH2  IN        3    NO      FORCED LOW
	 AH3  IN     1212    NO 
	 AH4  IN       11    NO      FORCED HI
	 AH5  IN     1412    NO 
	 AH6  IN        3    NO      FORCED LOW
	 AH7  IN      569    NO 
	 AH8  IN       83    NO      FORCED HI
	 AH9  IN      546    NO 
	 AH10  IN        3    NO      FORCED LOW
	 AH11  IN      233    NO 
	 AH12  IN       11    NO      FORCED HI
	 AH13  IN        3    NO      FORCED LOW
	 AH14  IN      113    NO 
	 AH15  IN       83    NO      FORCED HI
	 AH16  IN   
	 AH17  IN        3    NO      FORCED LOW
	 AH18  IN      178    NO 
	 AH19  IN       11    NO      FORCED HI
	 AH20  IN   
	 AH21  IN        3    NO      FORCED LOW
	 AH22  IN     1163    NO 
	 AH23  IN       11    NO      FORCED HI
	 AH24  IN       11    NO      FORCED HI
	 AJ2  IN       11    NO      FORCED HI
	 AJ3  IN      660    NO 
	 AJ4  IN       11    NO      FORCED HI
	 AJ5  IN      827    NO 
	 AJ6  IN      418    NO 
	 AJ7  IN      787    NO 
	 AJ08  IN      434    NO 
	 AJ9  IN      362    NO 
	 AJ10  IN      514    NO 
	 AJ11  IN      425    NO 
	 AJ12  IN      482    NO 
	 AJ13  IN      370    NO 
	 AJ14  IN      386    NO 
	 AJ15  IN      297    NO 
	 AJ16  IN      145    NO 
	 AJ17  IN      265    NO 
	 AJ18  IN     1516    NO 
	 AJ19  IN   
	 AJ20  IN     1475    NO 
	 AJ21  IN       11    NO      FORCED HI
	 AJ22  IN     1467    NO 
	 AJ23  IN     1443    NO 
	 AK3  IN     1299    NO 
	 AK4  IN        3    NO      FORCED LOW
	 AK5  IN      330    NO 
	 AK6  IN       83    NO      FORCED HI
	 AK7  IN      417    NO 
	 AK8  IN        3    NO      FORCED LOW
	 AK9  IN      481    NO 
	 AK10  IN       11    NO      FORCED HI
	 AK11  IN      442    NO 
	 AK12  IN        3    NO      FORCED LOW
	 AK13  IN       83    NO      FORCED HI
	 AK14  IN      338    NO 
	 AK15  IN        3    NO      FORCED LOW
	 AK16  IN      426    NO 
	 AK17  IN       11    NO      FORCED HI
	 AK18  IN      290    NO 
	 AK19  IN        3    NO      FORCED LOW
	 AK20  IN      186    NO 
	 AK21  IN       83    NO      FORCED HI
	 AK22  IN      218    NO 
	 AL4  IN       11    NO      FORCED HI
	 AL5  IN      811    NO 
	 AL6  IN      465    NO 
	 AL7  IN      828    NO 
	 AL8  IN      489    NO 
	 AL9  IN      788    NO 
	 AL10  IN      490    NO 
	 AL11  IN      273    NO 
	 AL12  IN      258    NO 
	 AL13  IN      337    NO 
	 AL14  IN      473    NO 
	 AL15  IN      210    NO 
	 AL16  IN     1556    NO 
	 AL17  IN      378    NO 
	 AL18  IN     1532    NO 
	 AL19  IN      322    NO 
	 AL20  IN     1468    NO 
	 AL21  IN       11    NO      FORCED HI
	 B3   IN     1676    NO 
	 B4   IN        3    NO      FORCED LOW
	 B5   IN      803    NO 
	 B6   IN       83    NO      FORCED HI
	 B7   IN   
	 B8   IN        3    NO      FORCED LOW
	 B9   IN      803    NO 
	 B10  IN       11    NO      FORCED HI
	 B11  IN      779    NO 
	 B12  IN        3    NO      FORCED LOW
	 B13  IN       83    NO      FORCED HI
	 B14  IN      748    NO 
	 B15  IN        3    NO      FORCED LOW
	 B16  IN      763    NO 
	 B17  IN       11    NO      FORCED HI
	 B18  IN        2    NO 
	 B19  IN        3    NO      FORCED LOW
	 B20  IN       57    NO 
	 B21  IN       83    NO      FORCED HI
	 B22  IN     1011    NO 
	 C2   IN       11    NO      FORCED HI
	 C3   IN   
	 C4   IN      657    NO 
	 C5   IN      650    NO 
	 C6   IN      803    NO 
	 C7   IN      625    NO 
	 C8   IN      803    NO 
	 C9   IN   
	 C10  IN      803    NO 
	 C11  IN      779    NO 
	 C12  IN      692    NO 
	 C13  IN      699    NO 
	 C14  IN      731    NO 
	 C15  IN       97    NO 
	 C16  IN     1539    NO 
	 C17  IN       58    NO 
	 C18  IN     1531    NO 
	 C19  IN        9    NO 
	 C20  IN       33    NO 
	 C21  IN   
	 C22  IN   
	 C23  IN       11    NO      FORCED HI
	 D1   IN      859    NO 
	 D2   IN        3    NO      FORCED LOW
	 D3   IN     1692    NO 
	 D4   IN       11    NO      FORCED HI
	 D5   IN      804    NO 
	 D6   IN        3    NO      FORCED LOW
	 D7   IN   
	 D8   IN       83    NO      FORCED HI
	 D9   IN      609    NO 
	 D10  IN        3    NO      FORCED LOW
	 D11  IN      779    NO 
	 D12  IN       11    NO      FORCED HI
	 D13  IN        3    NO      FORCED LOW
	 D14  IN       90    NO 
	 D15  IN       83    NO      FORCED HI
	 D16  IN     1563    NO 
	 D17  IN        3    NO      FORCED LOW
	 D18  IN     1132    NO 
	 D19  IN       11    NO      FORCED HI
	 D20  IN       73    NO 
	 D21  IN        3    NO      FORCED LOW
	 D22  IN      876    NO 
	 D23  IN       11    NO      FORCED HI
	 D24  IN       11    NO      FORCED HI
	 E1   IN   
	 E2   IN   
	 E3   IN   
	 E4   IN     1667    NO 
	 E5   IN      641    NO 
	 E6   IN   
	 E7   IN      649    NO 
	 E8   IN      633    NO 
	 E9   IN      594    NO 
	 E10  IN      803    NO 
	 E11  IN      675    NO 
	 E12  IN     1579    NO 
	 E13  IN      716    NO 
	 E14  IN      683    NO 
	 E15  IN       98    NO 
	 E16  IN     1555    NO 
	 E17  IN     1140    NO 
	 E18  IN     1139    NO 
	 E19  IN     1508    NO 
	 E20  IN       34    NO 
	 E21  IN      883    NO 
	 E22  IN     1459    NO 
	 E23  IN      708    NO 
	 E24  IN   
	 F1   IN     1052    NO 
	 F2   IN       11    NO      FORCED HI
	 F3   IN     1003    NO 
	 F4   IN        3    NO      FORCED LOW
	 F5   IN   
	 F6   IN       83    NO      FORCED HI
	 F7   IN     1619    NO 
	 F8   IN        3    NO      FORCED LOW
	 F9   IN      642    NO 
	 F10  IN       11    NO      FORCED HI
	 F11  IN     1596    NO 
	 F12  IN        3    NO      FORCED LOW
	 F13  IN       83    NO      FORCED HI
	 F14  IN       50    NO 
	 F15  IN        3    NO      FORCED LOW
	 F16  IN   
	 F17  IN       11    NO      FORCED HI
	 F18  IN     1148    NO 
	 F19  IN        3    NO      FORCED LOW
	 F20  IN     1483    NO 
	 F21  IN       11    NO      FORCED HI
	 F22  IN     1388    NO 
	 F23  IN        3    NO      FORCED LOW
	 F24  IN     1331    NO 
	 G1   IN      844    NO 
	 G2   IN   
	 G3   IN      835    NO 
	 G4   IN     1708    NO 
	 G5   IN     1636    NO 
	 G6   IN       11    NO      FORCED HI
	 G7   IN     1612    NO 
	 G8   IN      618    NO 
	 G9   IN   
	 G10  IN      803    NO 
	 G11  IN      668    NO 
	 G12  IN      691    NO 
	 G13  IN      724    NO 
	 G14  IN      578    NO 
	 G15  IN      764    NO 
	 G16  IN     1540    NO 
	 G17  IN   
	 G18  IN     1500    NO 
	 G19  IN     1076    NO 
	 G20  IN     1004    NO 
	 G21  IN     1035    NO 
	 G22  IN     1451    NO 
	 G23  IN     1380    NO 
	 G24  IN      756    NO 
	 H1   IN     1059    NO 
	 H2   IN        3    NO      FORCED LOW
	 H3   IN      996    NO 
	 H4   IN       11    NO      FORCED HI
	 H5   IN      812    NO 
	 H6   IN        3    NO      FORCED LOW
	 H7   IN      634    NO 
	 H8   IN       83    NO      FORCED HI
	 H9   IN      601    NO 
	 H10  IN        3    NO      FORCED LOW
	 H11  IN     1603    NO 
	 H12  IN       11    NO      FORCED HI
	 H13  IN        3    NO      FORCED LOW
	 H14  IN       66    NO 
	 H15  IN       83    NO      FORCED HI
	 H16  IN   
	 H17  IN        3    NO      FORCED LOW
	 H18  IN       26    NO 
	 H19  IN       83    NO      FORCED HI
	 H20  IN      707    NO 
	 H21  IN        3    NO      FORCED LOW
	 H22  IN     1395    NO 
	 H23  IN       83    NO      FORCED HI
	 H24  IN     1324    NO 
	 J01  IN      843    NO 
	 J2   IN   
	 J3   IN      916    NO 
	 J4   IN     1660    NO 
	 J5   IN      700    NO 
	 J6   IN      796    NO 
	 J7   IN      610    NO 
	 J8   IN   
	 J9   IN      804    NO 
	 J10  IN      803    NO 
	 J11  IN      779    NO 
	 J12  IN      676    NO 
	 J13  IN      585    NO 
	 J14  IN      586    NO 
	 J15  IN        3    NO      FORCED LOW
	 J16  IN     1564    NO 
	 J17  IN     1507    NO 
	 J18  IN       25    NO 
	 J19  IN     1084    NO 
	 J20  IN       11    NO      FORCED HI
	 J21  IN     1027    NO 
	 J22  IN       11    NO      FORCED HI
	 J23  IN     1387    NO 
	 J24  IN       11    NO      FORCED HI
	 K1   IN       11    NO      FORCED HI
	 K2   IN       83    NO      FORCED HI
	 K3   IN       11    NO      FORCED HI
	 K4   IN        3    NO      FORCED LOW
	 K5   IN      819    NO 
	 K6   IN       11    NO      FORCED HI
	 K7   IN      804    NO 
	 K8   IN        3    NO      FORCED LOW
	 K9   IN      626    NO 
	 K10  IN       11    NO      FORCED HI
	 K11  IN      779    NO 
	 K12  IN        3    NO      FORCED LOW
	 K13  IN       83    NO      FORCED HI
	 K14  IN      593    NO 
	 K15  IN        3    NO      FORCED LOW
	 K16  IN     1547    NO 
	 K17  IN       11    NO      FORCED HI
	 K18  IN       17    NO 
	 K19  IN        3    NO      FORCED LOW
	 K20  IN       11    NO      FORCED HI
	 K21  IN       83    NO      FORCED HI
	 K22  IN     1068    NO 
	 K23  IN        3    NO      FORCED LOW
	 K24  IN     1075    NO 
	 L1   IN      939    NO 
	 L2   IN     1700    NO 
	 L3   IN     1683    NO 
	 L4   IN     1651    NO 
	 L5   IN      795    NO 
	 L06  IN     1155    NO 
	 L7   IN       11    NO      FORCED HI
	 L8   IN     1611    NO 
	 L9   IN      617    NO 
	 L10  IN      803    NO 
	 L11  IN      803    NO 
	 L12  IN      779    NO 
	 L13  IN      740    NO 
	 L14  IN      105    NO 
	 L15  IN      771    NO 
	 L16  IN     1571    NO 
	 L17  IN     1515    NO 
	 L18  IN     1091    NO 
	 L19  IN     1092    NO 
	 L20  IN     1099    NO 
	 L21  IN     1020    NO 
	 L22  IN     1019    NO 
	 L23  IN     1012    NO 
	 L24  IN      964    NO 
	 M1   IN      923    NO 
	 M2   IN        3    NO      FORCED LOW
	 M3   IN      932    NO 
	 M4   IN       83    NO      FORCED HI
	 M5   IN     1715    NO 
	 M6   IN        3    NO      FORCED LOW
	 M7   IN       11    NO      FORCED HI
	 M8   IN       11    NO      FORCED HI
	 M9   IN      803    NO 
	 M10  IN        3    NO      FORCED LOW
	 M11  IN     1595    NO 
	 M12  IN       83    NO      FORCED HI
	 M13  IN        3    NO      FORCED LOW
	 M14  IN       65    NO 
	 M15  IN       83    NO      FORCED HI
	 M16  IN     1147    NO 
	 M17  IN        3    NO      FORCED LOW
	 M18  IN     1083    NO 
	 M19  IN       11    NO      FORCED HI
	 M20  IN     1028    NO 
	 M21  IN        3    NO      FORCED LOW
	 M22  IN      971    NO 
	 M23  IN       11    NO      FORCED HI
	 M24  IN      947    NO 
	 N1   IN      924    NO 
	 N2   IN      931    NO 
	 N3   IN      908    NO 
	 N4   IN      915    NO 
	 N5   IN       11    NO      FORCED HI
	 N6   IN      900    NO 
	 N7   IN      907    NO 
	 N8   IN       11    NO      FORCED HI
	 N9   IN      987    NO 
	 N10  IN      803    NO 
	 N11  IN   
	 N12  IN      779    NO 
	 N13  IN      715    NO 
	 N14  IN        1    NO 
	 N15  IN       89    NO 
	 N16  IN      867    NO 
	 N17  IN       11    NO      FORCED HI
	 N18  IN      956    NO 
	 N19  IN      963    NO 
	 N20  IN      948    NO 
	 N21  IN      955    NO 
	 N22  IN      940    NO 
	 N23  IN      884    NO 
	 N24  IN      891    NO 
	 P1   IN       11    NO      FORCED HI
	 P2   IN       11    NO      FORCED HI
	 P3   IN      979    NO 
	 P4   IN        3    NO      FORCED LOW
	 P5   IN      972    NO 
	 P6   IN       83    NO      FORCED HI
	 P7   IN       11    NO      FORCED HI
	 P8   IN        3    NO      FORCED LOW
	 P9   IN      980    NO 
	 P10  IN       83    NO      FORCED HI
	 P11  IN     1587    NO 
	 P12  IN        3    NO      FORCED LOW
	 P13  IN       83    NO      FORCED HI
	 P14  IN       49    NO 
	 P15  IN        3    NO      FORCED LOW
	 P16  IN       11    NO      FORCED HI
	 P17  IN       83    NO      FORCED HI
	 P18  IN      868    NO 
	 P19  IN        3    NO      FORCED LOW
	 P20  IN      860    NO 
	 P21  IN       11    NO      FORCED HI
	 P22  IN      875    NO 
	 P23  IN        3    NO      FORCED LOW
	 P24  IN       11    NO      FORCED HI
	 R1   IN     1707    NO 
	 R2   IN       11    NO      FORCED HI
	 R3   IN     1043    NO 
	 R4   IN     1668    NO 
	 R5   IN     1635    NO 
	 R6   IN     1036    NO 
	 R7   IN     1627    NO 
	 R8   IN      988    NO 
	 R9   IN      995    NO 
	 R10  IN     1044    NO 
	 R11  IN       83    NO      FORCED HI
	 R12  IN     1580    NO 
	 R13  IN       42    NO 
	 R14  IN        3    NO      FORCED LOW
	 R15  IN     1371    NO 
	 R16  IN      899    NO 
	 R17  IN      892    NO 
	 R18  IN     1499    NO 
	 R19  IN     1379    NO 
	 R20  IN     1484    NO 
	 R21  IN     1452    NO 
	 R22  IN     1372    NO 
	 R23  IN       11    NO      FORCED HI
	 R24  IN     1436    NO 
	 T1   IN     1699    NO 
	 T2   IN        3    NO      FORCED LOW
	 T3   IN     1060    NO 
	 T4   IN       11    NO      FORCED HI
	 T5   IN     1628    NO 
	 T6   IN        3    NO      FORCED LOW
	 T7   IN     1067    NO 
	 T8   IN       83    NO      FORCED HI
	 T9   IN     1051    NO 
	 T10  IN        3    NO      FORCED LOW
	 T11  IN     1108    NO 
	 T12  IN       83    NO      FORCED HI
	 T13  IN        3    NO      FORCED LOW
	 T14  IN     1364    NO 
	 T15  IN       83    NO      FORCED HI
	 T16  IN     1267    NO 
	 T17  IN        3    NO      FORCED LOW
	 T18  IN     1316    NO 
	 T19  IN       83    NO      FORCED HI
	 T20  IN     1315    NO 
	 T21  IN        3    NO      FORCED LOW
	 T22  IN     1308    NO 
	 T23  IN       83    NO      FORCED HI
	 T24  IN     1323    NO 
	 U1   IN       74    NO 
	 U2   IN       11    NO      FORCED HI
	 U3   IN     1116    NO 
	 U4   IN     1644    NO 
	 U5   IN       81    NO 
	 U6   IN     1123    NO 
	 U7   IN      106    NO 
	 U8   IN     1228    NO 
	 U9   IN     1235    NO 
	 U10  IN     1115    NO 
	 U11  IN        3    NO      FORCED LOW
	 U12  IN      506    NO 
	 U13  IN      450    NO 
	 U14  IN       83    NO      FORCED HI
	 U15  IN     1260    NO 
	 U16  IN     1187    NO 
	 U17  IN     1180    NO 
	 U18  IN     1523    NO 
	 U19  IN     1252    NO 
	 U20  IN     1491    NO 
	 U21  IN     1476    NO 
	 U22  IN     1259    NO 
	 U23  IN       11    NO      FORCED HI
	 U24  IN     1435    NO 
	 V1   IN       11    NO      FORCED HI
	 V2   IN       83    NO      FORCED HI
	 V3   IN     1204    NO 
	 V4   IN        3    NO      FORCED LOW
	 V5   IN     1211    NO 
	 V6   IN       11    NO      FORCED HI
	 V7   IN       11    NO      FORCED HI
	 V8   IN        3    NO      FORCED LOW
	 V9   IN     1203    NO 
	 V10  IN       83    NO      FORCED HI
	 V11  IN      202    NO 
	 V12  IN        3    NO      FORCED LOW
	 V13  IN       83    NO      FORCED HI
	 V14  IN      393    NO 
	 V15  IN        3    NO      FORCED LOW
	 V16  IN     1172    NO 
	 V17  IN       11    NO      FORCED HI
	 V18  IN     1524    NO 
	 V19  IN        3    NO      FORCED LOW
	 V20  IN     1164    NO 
	 V21  IN       11    NO      FORCED HI
	 V22  IN     1171    NO 
	 V23  IN        3    NO      FORCED LOW
	 V24  IN       11    NO      FORCED HI
	 W1   IN     1227    NO 
	 W2   IN     1220    NO 
	 W3   IN     1659    NO 
	 W4   IN     1275    NO 
	 W5   IN     1268    NO 
	 W6   IN     1283    NO 
	 W7   IN     1276    NO 
	 W8   IN       11    NO      FORCED HI
	 W9   IN     1196    NO 
	 W10  IN      530    NO 
	 W11  IN      505    NO 
	 W12  IN      553    NO 
	 W13  IN      458    NO 
	 W14  IN      394    NO 
	 W15  IN      162    NO 
	 W16  IN     1179    NO 
	 W17  IN       11    NO      FORCED HI
	 W18  IN      346    NO 
	 W19  IN      161    NO 
	 W20  IN       11    NO      FORCED HI
	 W21  IN      121    NO 
	 W22  IN      114    NO 
	 W23  IN     1195    NO 
	 W24  IN     1188    NO 
	 Y1   IN     1691    NO 
	 Y2   IN        3    NO      FORCED LOW
	 Y3   IN     1291    NO 
	 Y4   IN       83    NO      FORCED HI
	 Y5   IN     1340    NO 
	 Y6   IN        3    NO      FORCED LOW
	 Y7   IN     1363    NO 
	 Y8   IN       11    NO      FORCED HI
	 Y9   IN      561    NO 
	 Y10  IN        3    NO      FORCED LOW
	 Y11  IN      498    NO 
	 Y12  IN       83    NO      FORCED HI
	 Y13  IN        3    NO      FORCED LOW
	 Y14  IN      154    NO 
	 Y15  IN       83    NO      FORCED HI
	 Y16  IN      410    NO 
	 Y17  IN        3    NO      FORCED LOW
	 Y18  IN      193    NO 
	 Y19  IN       11    NO      FORCED HI
	 Y20  IN      241    NO 
	 Y21  IN        3    NO      FORCED LOW
	 Y22  IN      249    NO 
	 Y23  IN       11    NO      FORCED HI
	 Y24  OUT    1723    NO 

Results for U2 Isolation
----------------------------------------------
Outputs disabled at isolation level 1:
  U1.D1  U1.E3  U1.E4  U1.J4  U1.N2  U1.T4  U1.R4  U1.T5  U1.R5  U1.N7  U1.N8
  U1.R8  U1.T11  U1.P11  U1.R10  U1.T10  U1.P12  U1.P13  U1.N11  U1.T12  U1.T13
  U1.T14  U1.R14  U1.M16  U1.L14  U1.L15  U1.L16  U1.K15  U1.D15  U1.D16
  U1.E16  U1.D13  U1.D14  U1.A13  U1.B11  U1.A11  U1.B10  U1.A7  U1.B7
    by c:\tellabs\tellabslib.dtl/FBGA256/Disable #1

** No test steps generated for U2(c:\tellabs\tellabslib.dtl:VSC9186). 0/1
PROBLEM: No test program found for IC U3(SY89832U).
** WARNING: Did not find any valid output statement (OS) for U4.
At least one valid output statement(OS) is required for a test to be generated



-------------------------------------------
PIN RESULTS FOR U4 (VSC9186)
	 Pin  Type   Nail  Tested?  Comments
	 A4   IN      929    NO 
	 A5   IN      929    NO 
	 A6   IN      953    NO 
	 A7   IN      674    NO 
	 A8   IN      953    NO 
	 A9   IN      682    NO 
	 A10  IN     1505    NO 
	 A11  IN     1521    NO 
	 A12  IN      643    NO 
	 A13  IN      612    NO 
	 A14  IN      659    NO 
	 A15  IN       41    NO 
	 A16  IN     1545    NO 
	 A17  IN      754    NO 
	 A18  IN       10    NO 
	 A19  IN      761    NO 
	 A20  IN       18    NO 
	 A21  IN      762    NO 
	 AA1  IN      825    NO 
	 AA2  IN     1441    NO 
	 AA3  IN   
	 AA4  IN      841    NO 
	 AA5  IN      874    NO 
	 AA6  IN      873    NO 
	 AA7  IN     1489    NO 
	 AA8  IN       11    NO      FORCED HI
	 AA9  IN      130    NO 
	 AA10  IN      241    NO 
	 AA11  IN      169    NO 
	 AA12  IN      186    NO 
	 AA13  IN      145    NO 
	 AA14  IN      201    NO 
	 AA15  IN      482    NO 
	 AA16  IN       11    NO      FORCED HI
	 AA17  IN       11    NO      FORCED HI
	 AA18  IN      314    NO 
	 AA19  IN      546    NO 
	 AA20  IN      362    NO 
	 AA21  IN      530    NO 
	 AA22  IN      514    NO 
	 AA23  IN      441    NO 
	 AA24  IN      434    NO 
	 AB1  IN      858    NO 
	 AB2  IN       11    NO      FORCED HI
	 AB3  IN      857    NO 
	 AB4  IN        3    NO      FORCED LOW
	 AB5  IN       11    NO      FORCED HI
	 AB6  IN       83    NO      FORCED HI
	 AB7  IN      890    NO 
	 AB8  IN        3    NO      FORCED LOW
	 AB9  IN      177    NO 
	 AB10  IN       11    NO      FORCED HI
	 AB11  IN      154    NO 
	 AB12  IN        3    NO      FORCED LOW
	 AB13  IN       83    NO      FORCED HI
	 AB14  IN      146    NO 
	 AB15  IN        3    NO      FORCED LOW
	 AB16  IN      378    NO 
	 AB17  IN       11    NO      FORCED HI
	 AB18  IN      513    NO 
	 AB19  IN        3    NO      FORCED LOW
	 AB20  IN       11    NO      FORCED HI
	 AB21  IN       83    NO      FORCED HI
	 AB22  IN      521    NO 
	 AB23  IN        3    NO      FORCED LOW
	 AB24  IN      481    NO 
	 AC1  IN       11    NO      FORCED HI
	 AC2  IN     1402    NO 
	 AC3  IN       11    NO      FORCED HI
	 AC4  IN      842    NO 
	 AC5  IN       11    NO      FORCED HI
	 AC6  IN     1482    NO 
	 AC7  IN       11    NO      FORCED HI
	 AC8  IN      898    NO 
	 AC9  IN   
	 AC10  IN      193    NO 
	 AC11  IN      394    NO 
	 AC12  IN      162    NO 
	 AC13  IN      178    NO 
	 AC14  IN      153    NO 
	 AC15  IN      457    NO 
	 AC16  IN      322    NO 
	 AC17  IN      281    NO 
	 AC18  IN       11    NO      FORCED HI
	 AC19  IN      329    NO 
	 AC20  IN       11    NO      FORCED HI
	 AC21  IN      385    NO 
	 AC22  IN     1698    NO 
	 AC23  IN     1225    NO 
	 AC24  IN        3    NO      FORCED LOW
	 AD1  IN     1377    NO 
	 AD2  IN        3    NO      FORCED LOW
	 AD3  IN     1433    NO 
	 AD4  IN       11    NO      FORCED HI
	 AD5  IN      881    NO 
	 AD6  IN        3    NO      FORCED LOW
	 AD7  IN       11    NO      FORCED HI
	 AD8  IN       83    NO      FORCED HI
	 AD9  IN      298    NO 
	 AD10  IN        3    NO      FORCED LOW
	 AD11  IN      450    NO 
	 AD12  IN       11    NO      FORCED HI
	 AD13  IN        3    NO      FORCED LOW
	 AD14  IN      506    NO 
	 AD15  IN       83    NO      FORCED HI
	 AD16  IN      386    NO 
	 AD17  IN        3    NO      FORCED LOW
	 AD18  IN       11    NO      FORCED HI
	 AD19  IN       83    NO      FORCED HI
	 AD20  IN      538    NO 
	 AD21  IN        3    NO      FORCED LOW
	 AD22  IN     1217    NO 
	 AD23  IN       83    NO      FORCED HI
	 AD24  IN     1282    NO 
	 AE1  IN   
	 AE2  IN     1401    NO 
	 AE3  IN      579    NO 
	 AE4  IN      850    NO 
	 AE5  IN      833    NO 
	 AE6  IN      865    NO 
	 AE7  IN      409    NO 
	 AE8  IN      897    NO 
	 AE9  IN      209    NO 
	 AE10  IN      242    NO 
	 AE11  IN       11    NO      FORCED HI
	 AE12  IN      138    NO 
	 AE13  IN   
	 AE14  IN     1538    NO 
	 AE15  IN      337    NO 
	 AE16  IN      570    NO 
	 AE17  IN      562    NO 
	 AE18  IN      313    NO 
	 AE19  IN      569    NO 
	 AE20  IN      330    NO 
	 AE21  IN      561    NO 
	 AE22  IN     1666    NO 
	 AE23  IN     1226    NO 
	 AE24  IN       62    NO      FORCED HI
	 AF1  IN     1378    NO 
	 AF2  IN       83    NO      FORCED HI
	 AF3  IN     1457    NO 
	 AF4  IN        3    NO      FORCED LOW
	 AF5  IN      377    NO 
	 AF6  IN       83    NO      FORCED HI
	 AF7  IN      129    NO 
	 AF8  IN        3    NO      FORCED LOW
	 AF9  IN      266    NO 
	 AF10  IN       11    NO      FORCED HI
	 AF11  IN      346    NO 
	 AF12  IN        3    NO      FORCED LOW
	 AF13  IN       83    NO      FORCED HI
	 AF14  IN      489    NO 
	 AF15  IN        3    NO      FORCED LOW
	 AF16  IN      577    NO 
	 AF17  IN       11    NO      FORCED HI
	 AF18  IN      554    NO 
	 AF19  IN        3    NO      FORCED LOW
	 AF20  IN   
	 AF21  IN       11    NO      FORCED HI
	 AF22  IN     1218    NO 
	 AF23  IN        3    NO      FORCED LOW
	 AF24  IN     1281    NO 
	 AG1  IN      905    NO 
	 AG2  IN      882    NO 
	 AG3  IN   
	 AG4  IN      786    NO 
	 AG5  IN      938    NO 
	 AG6  IN      345    NO 
	 AG7  IN      122    NO 
	 AG8  IN      353    NO 
	 AG9  IN       11    NO      FORCED HI
	 AG10  IN      225    NO 
	 AG11  IN      978    NO 
	 AG12  IN      226    NO 
	 AG13  IN      354    NO 
	 AG14  IN      985    NO 
	 AG15  IN   
	 AG16  IN      338    NO 
	 AG17  IN      473    NO 
	 AG18  IN      289    NO 
	 AG19  IN      522    NO 
	 AG20  IN     1641    NO 
	 AG21  IN     1137    NO 
	 AG22  IN   
	 AG23  IN   
	 AG24  IN     1673    NO 
	 AH1  IN       11    NO      FORCED HI
	 AH2  IN        3    NO      FORCED LOW
	 AH3  IN      785    NO 
	 AH4  IN       11    NO      FORCED HI
	 AH5  IN      889    NO 
	 AH6  IN        3    NO      FORCED LOW
	 AH7  IN   
	 AH8  IN       83    NO      FORCED HI
	 AH9  IN      305    NO 
	 AH10  IN        3    NO      FORCED LOW
	 AH11  IN      393    NO 
	 AH12  IN       11    NO      FORCED HI
	 AH13  IN        3    NO      FORCED LOW
	 AH14  IN      202    NO 
	 AH15  IN       83    NO      FORCED HI
	 AH16  IN      458    NO 
	 AH17  IN        3    NO      FORCED LOW
	 AH18  IN      306    NO 
	 AH19  IN       11    NO      FORCED HI
	 AH20  IN      545    NO 
	 AH21  IN        3    NO      FORCED LOW
	 AH22  IN     1138    NO 
	 AH23  IN       11    NO      FORCED HI
	 AH24  IN       11    NO      FORCED HI
	 AJ2  IN       11    NO      FORCED HI
	 AJ3  IN      587    NO 
	 AJ4  IN       11    NO      FORCED HI
	 AJ5  IN      945    NO 
	 AJ6  IN      218    NO 
	 AJ7  IN      962    NO 
	 AJ08  IN      185    NO 
	 AJ9  IN      137    NO 
	 AJ10  IN   
	 AJ11  IN      265    NO 
	 AJ12  IN      402    NO 
	 AJ13  IN      426    NO 
	 AJ14  IN      257    NO 
	 AJ15  IN      273    NO 
	 AJ16  IN      449    NO 
	 AJ17  IN      425    NO 
	 AJ18  IN     1585    NO 
	 AJ19  IN      553    NO 
	 AJ20  IN     1634    NO 
	 AJ21  IN       11    NO      FORCED HI
	 AJ22  IN     1642    NO 
	 AJ23  IN     1682    NO 
	 AK3  IN      834    NO 
	 AK4  IN        3    NO      FORCED LOW
	 AK5  IN      170    NO 
	 AK6  IN       83    NO      FORCED HI
	 AK7  IN      249    NO 
	 AK8  IN        3    NO      FORCED LOW
	 AK9  IN      194    NO 
	 AK10  IN       11    NO      FORCED HI
	 AK11  IN      290    NO 
	 AK12  IN        3    NO      FORCED LOW
	 AK13  IN       83    NO      FORCED HI
	 AK14  IN      321    NO 
	 AK15  IN        3    NO      FORCED LOW
	 AK16  IN      370    NO 
	 AK17  IN       11    NO      FORCED HI
	 AK18  IN      442    NO 
	 AK19  IN        3    NO      FORCED LOW
	 AK20  IN      529    NO 
	 AK21  IN       83    NO      FORCED HI
	 AK22  IN      418    NO 
	 AL4  IN       11    NO      FORCED HI
	 AL5  IN      930    NO 
	 AL6  IN      210    NO 
	 AL7  IN      954    NO 
	 AL8  IN      250    NO 
	 AL9  IN      970    NO 
	 AL10  IN      161    NO 
	 AL11  IN      297    NO 
	 AL12  IN      410    NO 
	 AL13  IN      401    NO 
	 AL14  IN   
	 AL15  IN      465    NO 
	 AL16  IN     1577    NO 
	 AL17  IN      466    NO 
	 AL18  IN     1617    NO 
	 AL19  IN      433    NO 
	 AL20  IN     1633    NO 
	 AL21  IN       11    NO      FORCED HI
	 B3   IN     1418    NO 
	 B4   IN        3    NO      FORCED LOW
	 B5   IN      937    NO 
	 B6   IN       83    NO      FORCED HI
	 B7   IN   
	 B8   IN        3    NO      FORCED LOW
	 B9   IN      937    NO 
	 B10  IN       11    NO      FORCED HI
	 B11  IN      953    NO 
	 B12  IN        3    NO      FORCED LOW
	 B13  IN       83    NO      FORCED HI
	 B14  IN      635    NO 
	 B15  IN        3    NO      FORCED LOW
	 B16  IN      993    NO 
	 B17  IN       11    NO      FORCED HI
	 B18  IN        2    NO 
	 B19  IN        3    NO      FORCED LOW
	 B20  IN       57    NO 
	 B21  IN       83    NO      FORCED HI
	 B22  IN     1066    NO 
	 C2   IN       11    NO      FORCED HI
	 C3   IN   
	 C4   IN      730    NO 
	 C5   IN      738    NO 
	 C6   IN      937    NO 
	 C7   IN      665    NO 
	 C8   IN      937    NO 
	 C9   IN      690    NO 
	 C10  IN      937    NO 
	 C11  IN      953    NO 
	 C12  IN      603    NO 
	 C13  IN      588    NO 
	 C14  IN      644    NO 
	 C15  IN       97    NO 
	 C16  IN     1553    NO 
	 C17  IN       58    NO 
	 C18  IN     1601    NO 
	 C19  IN        9    NO 
	 C20  IN       33    NO 
	 C21  IN   
	 C22  IN     1665    NO 
	 C23  IN       11    NO      FORCED HI
	 D1   IN      914    NO 
	 D2   IN        3    NO      FORCED LOW
	 D3   IN     1425    NO 
	 D4   IN       11    NO      FORCED HI
	 D5   IN      929    NO 
	 D6   IN        3    NO      FORCED LOW
	 D7   IN      697    NO 
	 D8   IN       83    NO      FORCED HI
	 D9   IN      706    NO 
	 D10  IN        3    NO      FORCED LOW
	 D11  IN      953    NO 
	 D12  IN       11    NO      FORCED HI
	 D13  IN        3    NO      FORCED LOW
	 D14  IN       90    NO 
	 D15  IN       83    NO      FORCED HI
	 D16  IN     1609    NO 
	 D17  IN        3    NO      FORCED LOW
	 D18  IN     1113    NO 
	 D19  IN       11    NO      FORCED HI
	 D20  IN       73    NO 
	 D21  IN        3    NO      FORCED LOW
	 D22  IN     1017    NO 
	 D23  IN       11    NO      FORCED HI
	 D24  IN       11    NO      FORCED HI
	 E1   IN      913    NO 
	 E2   IN   
	 E3   IN   
	 E4   IN     1450    NO 
	 E5   IN      737    NO 
	 E6   IN     1497    NO 
	 E7   IN      689    NO 
	 E8   IN      729    NO 
	 E9   IN      673    NO 
	 E10  IN      937    NO 
	 E11  IN      595    NO 
	 E12  IN     1513    NO 
	 E13  IN      652    NO 
	 E14  IN      619    NO 
	 E15  IN       98    NO 
	 E16  IN     1569    NO 
	 E17  IN     1121    NO 
	 E18  IN     1114    NO 
	 E19  IN     1610    NO 
	 E20  IN       34    NO 
	 E21  IN     1018    NO 
	 E22  IN     1649    NO 
	 E23  IN      620    NO 
	 E24  IN     1681    NO 
	 F1   IN     1329    NO 
	 F2   IN       11    NO      FORCED HI
	 F3   IN     1274    NO 
	 F4   IN        3    NO      FORCED LOW
	 F5   IN   
	 F6   IN       83    NO      FORCED HI
	 F7   IN     1481    NO 
	 F8   IN        3    NO      FORCED LOW
	 F9   IN      746    NO 
	 F10  IN       11    NO      FORCED HI
	 F11  IN   
	 F12  IN        3    NO      FORCED LOW
	 F13  IN       83    NO      FORCED HI
	 F14  IN       50    NO 
	 F15  IN        3    NO      FORCED LOW
	 F16  IN     1537    NO 
	 F17  IN       11    NO      FORCED HI
	 F18  IN     1129    NO 
	 F19  IN        3    NO      FORCED LOW
	 F20  IN     1618    NO 
	 F21  IN       11    NO      FORCED HI
	 F22  IN     1369    NO 
	 F23  IN        3    NO      FORCED LOW
	 F24  IN     1306    NO 
	 G1   IN   
	 G2   IN   
	 G3   IN      921    NO 
	 G4   IN     1690    NO 
	 G5   IN     1458    NO 
	 G6   IN       11    NO      FORCED HI
	 G7   IN   
	 G8   IN      658    NO 
	 G9   IN   
	 G10  IN      937    NO 
	 G11  IN      596    NO 
	 G12  IN      611    NO 
	 G13  IN      651    NO 
	 G14  IN      745    NO 
	 G15  IN      977    NO 
	 G16  IN     1561    NO 
	 G17  IN   
	 G18  IN     1578    NO 
	 G19  IN     1090    NO 
	 G20  IN     1065    NO 
	 G21  IN     1713    NO 
	 G22  IN     1650    NO 
	 G23  IN     1361    NO 
	 G24  IN      994    NO 
	 H1   IN     1330    NO 
	 H2   IN        3    NO      FORCED LOW
	 H3   IN     1273    NO 
	 H4   IN       11    NO      FORCED HI
	 H5   IN      946    NO 
	 H6   IN        3    NO      FORCED LOW
	 H7   IN      681    NO 
	 H8   IN       83    NO      FORCED HI
	 H9   IN      713    NO 
	 H10  IN        3    NO      FORCED LOW
	 H11  IN     1506    NO 
	 H12  IN       11    NO      FORCED HI
	 H13  IN        3    NO      FORCED LOW
	 H14  IN       66    NO 
	 H15  IN       83    NO      FORCED HI
	 H16  IN   
	 H17  IN        3    NO      FORCED LOW
	 H18  IN       26    NO 
	 H19  IN       83    NO      FORCED HI
	 H20  IN      627    NO 
	 H21  IN        3    NO      FORCED LOW
	 H22  IN     1370    NO 
	 H23  IN       83    NO      FORCED HI
	 H24  IN     1305    NO 
	 J01  IN      906    NO 
	 J2   IN     1442    NO 
	 J3   IN     1193    NO 
	 J4   IN     1473    NO 
	 J5   IN      636    NO 
	 J6   IN      969    NO 
	 J7   IN      666    NO 
	 J8   IN   
	 J9   IN      929    NO 
	 J10  IN      937    NO 
	 J11  IN      953    NO 
	 J12  IN      604    NO 
	 J13  IN      698    NO 
	 J14  IN      705    NO 
	 J15  IN        3    NO      FORCED LOW
	 J16  IN     1546    NO 
	 J17  IN     1594    NO 
	 J18  IN       25    NO 
	 J19  IN     1097    NO 
	 J20  IN       11    NO      FORCED HI
	 J21  IN     1074    NO 
	 J22  IN       11    NO      FORCED HI
	 J23  IN     1362    NO 
	 J24  IN       11    NO      FORCED HI
	 K1   IN       11    NO      FORCED HI
	 K2   IN       83    NO      FORCED HI
	 K3   IN       11    NO      FORCED HI
	 K4   IN        3    NO      FORCED LOW
	 K5   IN      961    NO 
	 K6   IN       11    NO      FORCED HI
	 K7   IN      929    NO 
	 K8   IN        3    NO      FORCED LOW
	 K9   IN      714    NO 
	 K10  IN       11    NO      FORCED HI
	 K11  IN      953    NO 
	 K12  IN        3    NO      FORCED LOW
	 K13  IN       83    NO      FORCED HI
	 K14  IN      721    NO 
	 K15  IN        3    NO      FORCED LOW
	 K16  IN     1570    NO 
	 K17  IN       11    NO      FORCED HI
	 K18  IN       17    NO 
	 K19  IN        3    NO      FORCED LOW
	 K20  IN       11    NO      FORCED HI
	 K21  IN       83    NO      FORCED HI
	 K22  IN     1082    NO 
	 K23  IN        3    NO      FORCED LOW
	 K24  IN     1089    NO 
	 L1   IN     1210    NO 
	 L2   IN     1409    NO 
	 L3   IN     1434    NO 
	 L4   IN     1449    NO 
	 L5   IN      922    NO 
	 L06  IN     1130    NO 
	 L7   IN       11    NO      FORCED HI
	 L8   IN     1498    NO 
	 L9   IN      722    NO 
	 L10  IN      937    NO 
	 L11  IN      937    NO 
	 L12  IN      953    NO 
	 L13  IN      753    NO 
	 L14  IN      105    NO 
	 L15  IN      986    NO 
	 L16  IN     1554    NO 
	 L17  IN     1593    NO 
	 L18  IN     1098    NO 
	 L19  IN     1105    NO 
	 L20  IN     1106    NO 
	 L21  IN     1073    NO 
	 L22  IN     1714    NO 
	 L23  IN     1721    NO 
	 L24  IN     1057    NO 
	 M1   IN     1194    NO 
	 M2   IN        3    NO      FORCED LOW
	 M3   IN     1209    NO 
	 M4   IN       83    NO      FORCED HI
	 M5   IN     1697    NO 
	 M6   IN        3    NO      FORCED LOW
	 M7   IN       11    NO      FORCED HI
	 M8   IN       11    NO      FORCED HI
	 M9   IN      937    NO 
	 M10  IN        3    NO      FORCED LOW
	 M11  IN     1514    NO 
	 M12  IN       83    NO      FORCED HI
	 M13  IN        3    NO      FORCED LOW
	 M14  IN       65    NO 
	 M15  IN       83    NO      FORCED HI
	 M16  IN     1122    NO 
	 M17  IN        3    NO      FORCED LOW
	 M18  IN     1729    NO 
	 M19  IN       11    NO      FORCED HI
	 M20  IN     1081    NO 
	 M21  IN        3    NO      FORCED LOW
	 M22  IN     1058    NO 
	 M23  IN       11    NO      FORCED HI
	 M24  IN     1034    NO 
	 N1   IN     1201    NO 
	 N2   IN     1202    NO 
	 N3   IN     1185    NO 
	 N4   IN     1186    NO 
	 N5   IN       11    NO      FORCED HI
	 N6   IN     1177    NO 
	 N7   IN     1178    NO 
	 N8   IN       11    NO      FORCED HI
	 N9   IN     1258    NO 
	 N10  IN      937    NO 
	 N11  IN     1530    NO 
	 N12  IN      953    NO 
	 N13  IN      628    NO 
	 N14  IN        1    NO 
	 N15  IN       89    NO 
	 N16  IN     1002    NO 
	 N17  IN       11    NO      FORCED HI
	 N18  IN     1049    NO 
	 N19  IN     1050    NO 
	 N20  IN     1041    NO 
	 N21  IN     1042    NO 
	 N22  IN     1706    NO 
	 N23  IN     1722    NO 
	 N24  IN     1025    NO 
	 P1   IN       11    NO      FORCED HI
	 P2   IN       11    NO      FORCED HI
	 P3   IN     1250    NO 
	 P4   IN        3    NO      FORCED LOW
	 P5   IN     1249    NO 
	 P6   IN       83    NO      FORCED HI
	 P7   IN       11    NO      FORCED HI
	 P8   IN        3    NO      FORCED LOW
	 P9   IN     1257    NO 
	 P10  IN       83    NO      FORCED HI
	 P11  IN     1522    NO 
	 P12  IN        3    NO      FORCED LOW
	 P13  IN       83    NO      FORCED HI
	 P14  IN       49    NO 
	 P15  IN        3    NO      FORCED LOW
	 P16  IN       11    NO      FORCED HI
	 P17  IN       83    NO      FORCED HI
	 P18  IN     1009    NO 
	 P19  IN        3    NO      FORCED LOW
	 P20  IN     1001    NO 
	 P21  IN       11    NO      FORCED HI
	 P22  IN     1010    NO 
	 P23  IN        3    NO      FORCED LOW
	 P24  IN       11    NO      FORCED HI
	 R1   IN     1410    NO 
	 R2   IN       11    NO      FORCED HI
	 R3   IN     1314    NO 
	 R4   IN     1466    NO 
	 R5   IN   
	 R6   IN     1313    NO 
	 R7   IN     1490    NO 
	 R8   IN     1265    NO 
	 R9   IN     1266    NO 
	 R10  IN     1321    NO 
	 R11  IN       83    NO      FORCED HI
	 R12  IN     1529    NO 
	 R13  IN       42    NO 
	 R14  IN        3    NO      FORCED LOW
	 R15  IN     1346    NO 
	 R16  IN     1033    NO 
	 R17  IN     1026    NO 
	 R18  IN     1586    NO 
	 R19  IN     1354    NO 
	 R20  IN     1625    NO 
	 R21  IN     1658    NO 
	 R22  IN     1353    NO 
	 R23  IN       11    NO      FORCED HI
	 R24  IN     1689    NO 
	 T1   IN     1417    NO 
	 T2   IN        3    NO      FORCED LOW
	 T3   IN     1337    NO 
	 T4   IN       11    NO      FORCED HI
	 T5   IN     1474    NO 
	 T6   IN        3    NO      FORCED LOW
	 T7   IN     1338    NO 
	 T8   IN       83    NO      FORCED HI
	 T9   IN     1322    NO 
	 T10  IN        3    NO      FORCED LOW
	 T11  IN     1385    NO 
	 T12  IN       83    NO      FORCED HI
	 T13  IN        3    NO      FORCED LOW
	 T14  IN     1345    NO 
	 T15  IN       83    NO      FORCED HI
	 T16  IN     1242    NO 
	 T17  IN        3    NO      FORCED LOW
	 T18  IN     1297    NO 
	 T19  IN       83    NO      FORCED HI
	 T20  IN     1290    NO 
	 T21  IN        3    NO      FORCED LOW
	 T22  IN     1289    NO 
	 T23  IN       83    NO      FORCED HI
	 T24  IN     1298    NO 
	 U1   IN       74    NO 
	 U2   IN       11    NO      FORCED HI
	 U3   IN     1393    NO 
	 U4   IN     1465    NO 
	 U5   IN       81    NO 
	 U6   IN     1394    NO 
	 U7   IN      106    NO 
	 U8   IN      802    NO 
	 U9   IN      801    NO 
	 U10  IN     1386    NO 
	 U11  IN        3    NO      FORCED LOW
	 U12  IN   
	 U13  IN      217    NO 
	 U14  IN       83    NO      FORCED HI
	 U15  IN     1241    NO 
	 U16  IN     1162    NO 
	 U17  IN     1161    NO 
	 U18  IN     1562    NO 
	 U19  IN     1233    NO 
	 U20  IN     1626    NO 
	 U21  IN     1657    NO 
	 U22  IN     1234    NO 
	 U23  IN       11    NO      FORCED HI
	 U24  IN     1674    NO 
	 V1   IN       11    NO      FORCED HI
	 V2   IN       83    NO      FORCED HI
	 V3   IN      777    NO 
	 V4   IN        3    NO      FORCED LOW
	 V5   IN      778    NO 
	 V6   IN       11    NO      FORCED HI
	 V7   IN       11    NO      FORCED HI
	 V8   IN        3    NO      FORCED LOW
	 V9   IN      770    NO 
	 V10  IN       83    NO      FORCED HI
	 V11  IN      113    NO 
	 V12  IN        3    NO      FORCED LOW
	 V13  IN       83    NO      FORCED HI
	 V14  IN      233    NO 
	 V15  IN        3    NO      FORCED LOW
	 V16  IN     1153    NO 
	 V17  IN       11    NO      FORCED HI
	 V18  IN     1602    NO 
	 V19  IN        3    NO      FORCED LOW
	 V20  IN     1145    NO 
	 V21  IN       11    NO      FORCED HI
	 V22  IN     1146    NO 
	 V23  IN        3    NO      FORCED LOW
	 V24  IN       11    NO      FORCED HI
	 W1   IN      794    NO 
	 W2   IN      793    NO 
	 W3   IN     1426    NO 
	 W4   IN      810    NO 
	 W5   IN      809    NO 
	 W6   IN      818    NO 
	 W7   IN      817    NO 
	 W8   IN       11    NO      FORCED HI
	 W9   IN      769    NO 
	 W10  IN      274    NO 
	 W11  IN      114    NO 
	 W12  IN   
	 W13  IN   
	 W14  IN      361    NO 
	 W15  IN      474    NO 
	 W16  IN     1154    NO 
	 W17  IN       11    NO      FORCED HI
	 W18  IN      282    NO 
	 W19  IN      490    NO 
	 W20  IN       11    NO      FORCED HI
	 W21  IN      498    NO 
	 W22  IN      505    NO 
	 W23  IN     1170    NO 
	 W24  IN     1169    NO 
	 Y1   IN   
	 Y2   IN        3    NO      FORCED LOW
	 Y3   IN      826    NO 
	 Y4   IN       83    NO      FORCED HI
	 Y5   IN      849    NO 
	 Y6   IN        3    NO      FORCED LOW
	 Y7   IN      866    NO 
	 Y8   IN       11    NO      FORCED HI
	 Y9   IN      234    NO 
	 Y10  IN        3    NO      FORCED LOW
	 Y11  IN      121    NO 
	 Y12  IN       83    NO      FORCED HI
	 Y13  IN        3    NO      FORCED LOW
	 Y14  IN      369    NO 
	 Y15  IN       83    NO      FORCED HI
	 Y16  IN      258    NO 
	 Y17  IN        3    NO      FORCED LOW
	 Y18  IN      497    NO 
	 Y19  IN       11    NO      FORCED HI
	 Y20  IN      537    NO 
	 Y21  IN        3    NO      FORCED LOW
	 Y22  IN      417    NO 
	 Y23  IN       11    NO      FORCED HI
	 Y24  OUT    1705    NO 

Results for U4 Isolation
----------------------------------------------
Outputs disabled at isolation level 1:
  U1.G4  U1.E1  U1.K2  U1.K1  U1.K4  U1.K5  U1.L1  U1.L2  U1.M1  U1.M3  U1.L3
  U1.N3  U1.N4  U1.L4  U1.M4  U1.T4  U1.R4  U1.T5  U1.R5  U1.N7  U1.N8  U1.R8
  U1.T11  U1.P11  U1.R10  U1.T10  U1.P12  U1.P13  U1.N11  U1.T12  U1.T13
  U1.T14  U1.L14  U1.K16  U1.J12  U1.G15  U1.C16  U1.D13  U1.A6
    by c:\tellabs\tellabslib.dtl/FBGA256/Disable #1

Outputs not isolated at isolation level 1:
  U1.G2  (model has no isolations)


Nodes that failed to be isolated <level>
  JTAG_FPGA_TDO_9186_1 (579) <1>

** No test steps generated for U4(c:\tellabs\tellabslib.dtl:VSC9186). 0/2
PROBLEM: No test program found for IC U5(SY58012U).
PROBLEM: No test program found for IC U6(74LVC1T45).

* Unbussed ICs Tested/Untested/ATO Replaced: 0/2

Results for Bussed ICs
----------------------


-------------------------------------------
PIN RESULTS FOR U1 (FBGA256)
	 Pin  Type   Nail  Tested?  Comments
	 C3   OUTRI   316    NO      IOC3
	 F4   OUTRI   331    NO      IOF4
	 C1   BITRI   300    YES     IOC1
	 C2   BITRI		     IOC2 DEFAULTED HI
	 D3   BITRI   115    YES     IOD3
	 D4   BITRI		     IOD4 DEFAULTED HI
	 F3   BITRI		     IOF3 DEFAULTED HI
	 D2   BITRI   315    YES     IOD2
	 D1   BITRI   650    YES     IOD1
	 E3   BITRI   618    YES     IOE3
	 E4   BITRI   617    YES     IOE4
	 G4   BITRI   697    YES     IOG4
	 E1   BITRI   681    YES     IOE1
	 E2   BITRI   107    YES     IOE2
	 K2   BITRI   682    YES     IOK2
	 K1   BITRI   658    YES     IOK1
	 K4   BITRI   737    YES     IOK4
	 K5   BITRI   738    YES     IOK5
	 L1   BITRI   714    YES     IOL1
	 L2   BITRI   674    YES     IOL2
	 J4   BITRI		     IOJ4 DEFAULTED HI
	 M1   BITRI   713    YES     IOM1
	 M2   BITRI   308    YES     IOM2
	 M3   BITRI   690    YES     IOM3
	 L3   BITRI   706    YES     IOL3
	 N1   BITRI   100    YES     ION1
	 N2   BITRI   585    YES     ION2
	 P1   BITRI    99    YES     IOP1
	 P2   BITRI    92    YES     IOP2
	 N3   BITRI   722    YES     ION3
	 N4   BITRI   730    YES     ION4
	 P3   BITRI   291    YES     IOP3
	 L4   BITRI   673    YES     IOL4
	 M4   BITRI   729    YES     IOM4
	 R3   BITRI   323    YES     IOR3
	 T3   BITRI   307    YES     IOT3
	 P5   BITRI   132    YES     IOP5
	 P4   BITRI   108    YES     IOP4
	 T4   BITRI    73    YES     IOT4
	 R4   BITRI    18    YES     IOR4
	 T5   BITRI    17    YES     IOT5
	 R5   BITRI    25    YES     IOR5
	 N7   BITRI    26    YES     ION7
	 T6   BITRI   244    YES     IOT6
	 R6   BITRI   243    YES     IOR6
	 P6   BITRI   268    YES     IOP6
	 N6   BITRI   267    YES     ION6
	 N8   BITRI    34    YES     ION8
	 T7   BITRI   251    YES     IOT7
	 R7   BITRI   252    YES     IOR7
	 T8   BITRI   260    YES     IOT8
	 R8   BITRI    33    YES     IOR8
	 T11  BITRI    10    YES     IOT11
	 R11  BITRI   259    YES     IOR11
	 P11  BITRI    42    YES     IOP11
	 R10  BITRI     1    YES     IOR10
	 T10  BITRI     9    YES     IOT10
	 P12  BITRI    49    YES     IOP12
	 P13  BITRI    65    YES     IOP13
	 N11  BITRI    41    YES     ION11
	 T12  BITRI    50    YES     IOT12
	 R12  BITRI		     IOR12 DEFAULTED HI
	 T13  BITRI     2    YES     IOT13
	 R13  BITRI   356    YES     IOR13
	 T14  BITRI    58    YES     IOT14
	 R14  BITRI   642    YES     IOR14
	 K13  BITRI   211    YES     IOK13
	 N13  BITRI   203    YES     ION13
	 N14  BITRI   372    YES     ION14
	 P15  BITRI   163    YES     IOP15
	 P16  BITRI   164    YES     IOP16
	 N15  BITRI   172    YES     ION15
	 N16  BITRI   171    YES     ION16
	 M14  BITRI   179    YES     IOM14
	 P14  BITRI   156    YES     IOP14
	 M15  BITRI   204    YES     IOM15
	 M16  BITRI   586    YES     IOM16
	 L14  BITRI    66    YES     IOL14
	 L15  BITRI   602    YES     IOL15
	 L16  BITRI		     IOL16 DEFAULTED HI
	 K16  BITRI		     IOK16 DEFAULTED HI
	 K15  BITRI   641    YES     IOK15
	 H12  BITRI   212    YES     IOH12
	 J12  BITRI   666    YES     IOJ12
	 G16  BITRI   180    YES     IOG16
	 G15  BITRI   746    YES     IOG15
	 F15  BITRI   187    YES     IOF15
	 F16  BITRI   188    YES     IOF16
	 H13  BITRI   219    YES     IOH13
	 G12  BITRI   227    YES     IOG12
	 G13  BITRI   220    YES     IOG13
	 E13  BITRI   235    YES     IOE13
	 F13  BITRI   228    YES     IOF13
	 D15  BITRI   633    YES     IOD15
	 D16  BITRI		     IOD16 DEFAULTED HI
	 E15  BITRI   196    YES     IOE15
	 E16  BITRI   609    YES     IOE16
	 F14  BITRI   195    YES     IOF14
	 C15  BITRI   236    YES     IOC15
	 C16  BITRI   705    YES     IOC16
	 C14  BITRI   364    YES     IOC14
	 D13  BITRI    57    YES     IOD13
	 E14  BITRI   371    YES     IOE14
	 D14  BITRI   657    YES     IOD14
	 B14  BITRI   275    YES     IOB14
	 A14  BITRI   275    YES     IOA14
	 C13  BITRI		     IOC13 DEFAULTED HI
	 C12  BITRI		     IOC12 DEFAULTED HI
	 B13  BITRI   155    YES     IOB13
	 A13  BITRI   601    YES     IOA13
	 B12  BITRI   363    YES     IOB12
	 A12  BITRI   355    YES     IOA12
	 C11  BITRI		     IOC11 DEFAULTED HI
	 B11  BITRI   594    YES     IOB11
	 A11  BITRI   626    YES     IOA11
	 B10  BITRI		     IOB10 DEFAULTED HI
	 A10  BITRI   348    YES     IOA10
	 D9   BITRI   147    YES     IOD9
	 D11  BITRI   292    YES     IOD11
	 D10  BITRI   148    YES     IOD10
	 A7   BITRI   610    YES     IOA7
	 B7   BITRI   634    YES     IOB7
	 D8   BITRI   340    YES     IOD8
	 B6   BITRI   139    YES     IOB6
	 A6   BITRI   698    YES     IOA6
	 D7   BITRI   339    YES     IOD7
	 D6   BITRI   332    YES     IOD6
	 C6   BITRI   140    YES     IOC6
	 C5   BITRI   324    YES     IOC5
	 C4   BITRI   116    YES     IOC4
	 B5   BITRI   131    YES     IOB5
	 A5   BITRI    91    YES     IOA5
	 B4   BITRI   123    YES     IOB4
	 A4   BITRI   124    YES     IOA4
	 A3   BITRI		     IOA3 DEFAULTED HI
	 B3   BITRI		     IOB3 DEFAULTED HI
	 H2   IN      721    YES     CLK0
	 H1   IN      284    YES     CLK1
	 J2   IN      625    YES     CLK2
	 J1   IN      299    YES     CLK3
	 H16  IN      379    YES     CLK4
	 H15  IN   		     CLK5 DEFAULTED HI
	 J15  IN      649    YES     CLK6
	 J16  IN      578    YES     CLK7
	 A9   IN      593    YES     CLK8
	 B9   IN      689    YES     CLK9
	 A8   IN   		     CLK10 DEFAULTED HI
	 B8   IN   		     CLK11 DEFAULTED HI
	 N10  IN      347    YES     CLK12
	 N9   IN        4    HI      CLK13 FORCED HI
	 R9   IN      665    YES     CLK14
	 T9   IN      745    YES     CLK15
	 F1   IN      283    YES     DATA0
	 H4   IN      276    YES     DCLK
	 J13  IN       85    HI      MSEL0 FORCED HI
	 K12  IN       84    LOW     MSEL1 FORCED LOW
	 L13  ANA      67
	 G5   GND      80
	 J5   ANA      61
	 M13  ANA      64
	 F2   IN       81    YES     TCK
	 G1   IN       74    YES     TMS
	 H5   IN       82    YES     TDI
	 G2   OUTRI   579    YES     TDO
	 E5   POWER    63    NO      VCC1 FORCED HI
	 L6   POWER    63    NO      VCC2 FORCED HI
	 M5   POWER    63    NO      VCC3 FORCED HI
	 L11  POWER    63    NO      VCC4 FORCED HI
	 M12  POWER    63    NO      VCC5 FORCED HI
	 F11  POWER    63    NO      VCC6 FORCED HI
	 E12  POWER    63    NO      VCC7 FORCED HI
	 F6   POWER    63    NO      VCC8 FORCED HI
	 F9   POWER     4    NO      VCC9 FORCED HI
	 F10  POWER     4    NO      VCC10 FORCED HI
	 G7   POWER     4    NO      VCC11 FORCED HI
	 G9   POWER     4    NO      VCC12 FORCED HI
	 G11  POWER     4    NO      VCC13 FORCED HI
	 H7   POWER     4    NO      VCC14 FORCED HI
	 H10  POWER     4    NO      VCC15 FORCED HI
	 H11  POWER     4    NO      VCC16 FORCED HI
	 J6   POWER     4    NO      VCC17 FORCED HI
	 J7   POWER     4    NO      VCC18 FORCED HI
	 J10  POWER     4    NO      VCC19 FORCED HI
	 K6   POWER     4    NO      VCC20 FORCED HI
	 K8   POWER     4    NO      VCC21 FORCED HI
	 K10  POWER     4    NO      VCC22 FORCED HI
	 L7   POWER     4    NO      VCC23 FORCED HI
	 L8   POWER     4    NO      VCC24 FORCED HI
	 B1   POWER    12    NO      VCC25 FORCED HI
	 G3   POWER    12    NO      VCC26 FORCED HI
	 K3   POWER    12    NO      VCC27 FORCED HI
	 R1   POWER    12    NO      VCC28 FORCED HI
	 M7   POWER    12    NO      VCC29 FORCED HI
	 P7   POWER    12    NO      VCC30 FORCED HI
	 T2   POWER    12    NO      VCC31 FORCED HI
	 M10  POWER    12    NO      VCC32 FORCED HI
	 P10  POWER    12    NO      VCC33 FORCED HI
	 T15  POWER    12    NO      VCC34 FORCED HI
	 K14  POWER    12    NO      VCC35 FORCED HI
	 R16  POWER    12    NO      VCC36 FORCED HI
	 B16  POWER    12    NO      VCC37 FORCED HI
	 G14  POWER    12    NO      VCC38 FORCED HI
	 A15  POWER    12    NO      VCC39 FORCED HI
	 C10  POWER    12    NO      VCC40 FORCED HI
	 E10  POWER    12    NO      VCC41 FORCED HI
	 A2   POWER    12    NO      VCC42 FORCED HI
	 C7   POWER    12    NO      VCC43 FORCED HI
	 E7   POWER    12    NO      VCC44 FORCED HI
	 D5   GND       3    NO      GND1 FORCED LOW
	 F5   GND       3    NO      GND2 FORCED LOW
	 L5   GND       3    NO      GND3 FORCED LOW
	 N5   GND       3    NO      GND4 FORCED LOW
	 M6   GND       3    NO      GND5 FORCED LOW
	 M11  GND       3    NO      GND6 FORCED LOW
	 N12  GND       3    NO      GND7 FORCED LOW
	 L12  GND       3    NO      GND8 FORCED LOW
	 F12  GND       3    NO      GND9 FORCED LOW
	 D12  GND       3    NO      GND10 FORCED LOW
	 E11  GND       3    NO      GND11 FORCED LOW
	 E6   GND       3    NO      GND12 FORCED LOW
	 F7   GND       3    NO      GND13 FORCED LOW
	 F8   GND       3    NO      GND14 FORCED LOW
	 G6   GND       3    NO      GND15 FORCED LOW
	 G8   GND       3    NO      GND16 FORCED LOW
	 G10  GND       3    NO      GND17 FORCED LOW
	 H6   GND       3    NO      GND18 FORCED LOW
	 H8   GND       3    NO      GND19 FORCED LOW
	 H9   GND       3    NO      GND20 FORCED LOW
	 J8   GND       3    NO      GND21 FORCED LOW
	 J9   GND       3    NO      GND22 FORCED LOW
	 J11  GND       3    NO      GND23 FORCED LOW
	 K7   GND       3    NO      GND24 FORCED LOW
	 K9   GND       3    NO      GND25 FORCED LOW
	 K11  GND       3    NO      GND26 FORCED LOW
	 L9   GND       3    NO      GND27 FORCED LOW
	 L10  GND       3    NO      GND28 FORCED LOW
	 A1   GND       3    NO      GND29 FORCED LOW
	 A16  GND       3    NO      GND30 FORCED LOW
	 B2   GND       3    NO      GND31 FORCED LOW
	 B15  GND       3    NO      GND32 FORCED LOW
	 C8   GND       3    NO      GND33 FORCED LOW
	 C9   GND       3    NO      GND34 FORCED LOW
	 E8   GND       3    NO      GND35 FORCED LOW
	 E9   GND       3    NO      GND36 FORCED LOW
	 H3   GND       3    NO      GND37 FORCED LOW
	 H14  GND       3    NO      GND38 FORCED LOW
	 J3   GND       3    NO      GND39 FORCED LOW
	 J14  GND       3    NO      GND40 FORCED LOW
	 M8   GND       3    NO      GND41 FORCED LOW
	 M9   GND       3    NO      GND42 FORCED LOW
	 P8   GND       3    NO      GND43 FORCED LOW
	 P9   GND       3    NO      GND44 FORCED LOW
	 R2   GND       3    NO      GND45 FORCED LOW
	 R15  GND       3    NO      GND46 FORCED LOW
	 T1   GND       3    NO      GND47 FORCED LOW
	 T16  GND       3    NO      GND48 FORCED LOW
Message: 
THIS MODEL WAS GENERATED AUTOMATICALLY USING GR BasicSCAN !
Message: 
Version 4.0 Template: 4.0.1
  327 Potential test step(s) generated for U1(c:\tellabs\tellabslib.dtl:FBGA256). 1/2
========================================================================
sy:\0653D_mezzanine.dtp         DTG BACKDRIVE REPORT  22-APR-09 15:52:37
========================================================================
TEST U2:  for device U2 (VSC9186)
NO pins backdriven.
Estimated burst duration is 196.000 us.
------------------------------------------------------------------------

TEST U4:  for device U4 (VSC9186)
NO pins backdriven.
Estimated burst duration is 196.000 us.
------------------------------------------------------------------------

TEST U1:  for device U1 (FBGA256)
NO pins backdriven.
Estimated burst duration is   5.094 ms.
------------------------------------------------------------------------



========================================================================
                                BACKDRIVE REPORT SUMMARY
========================================================================

Device                          Tests       Max Pins    Max Duration
------------------------------------------------------------------------
Overall                            0           0         ----

Summary of Digital Test Program sy:\0653D_mezzanine.dtp


 **    1 ICs Tested
 **    2 ICs Untested
	 They are:	U2	U4

 ** 3 Problems Detected


Results for BUS275 Isolation
----------------------------------------------
Bus device outputs disabled:
  U1.B14  U1.A14
    by c:\tellabs\tellabslib.dtl/FBGA256/Disable #1


BUS275    BUS WIDTH: 		1
	  # OF FORCES: 		0
	  # OF DISABLES: 	1
	  BUS NAILS COVERED: 	275
	  BUSTEST COVERS:       U1

	     

END of Digital Automatic Test Generation.
	0 library errors, 3 library problems.

MERGE: Generate Mode (mrg.exe__494)

	Input files:
		sy:\0653D_mezzanine.dtp
		sy:0653D_mezzanine.ptp
		sy:\0653D_mezzanine.alp

	Output file:
		sy:\0653D_mezzanine.dtp

	0 warnings.
	0 errors.

MERGE: Generate Mode Completed.

